title: Forge Labs Blog
description: 中小製造業のためのAI業務効率化情報。AIプロンプトテンプレート集の制作・販売をしています。
theme: minima
markdown: kramdown
show_excerpts: true
header_pages:
  - about.md
plugins:
  - jekyll-feed
  - jekyll-sitemap

url: "https://forge-labs0621.github.io"
baseurl: "/forge-labs-blog"
lang: ja
webmaster_verifications:
  google: rj5q6pmLh7aLnjW9asqHQ1ZqWa4A6fhhVjCmpMwcQbo
  bing: 40AD9387BE2F1C30686431136561AACD
